

services:
  redmine:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: password
      REDMINE_DB_DATABASE: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
      TZ: Asia/Kolkata
    volumes:
      - redmine_data:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: redmine
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  redmine_data:
  redmine_plugins:
  db_data:
